export * from './approximately';
export * from './clamp';
export * from './divideWithoutRemainder';
export * from './getNearestByStep';
export * from './getPointsExtremeValues';
export * from './isClosedLine';
export * from './logarithm';
export * from './toFixed';
export * from './truncToDecimals';
